package com.vpalz.hotellosterrenos.entity;

import jakarta.persistence.*;
import lombok.Data;

import java.util.List;

/**
 * Represents a floor in the hotel, including details such as its name, theme, and associated rooms.
 * This entity is mapped to the "floors" table in the database.
 */
@Data
@Entity
@Table(name = "floors")
public class Floor {

    /**
     * Unique identifier for the floor.
     * This value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the floor, typically used for identification or descriptive purposes.
     */
    private String name;

    /**
     * Theme of the floor, representing its unique design or concept.
     */
    private String theme;

    /**
     * Floor number within the building, indicating its relative position (e.g., 1 for ground floor).
     */
    private Integer number;

    /**
     * List of rooms located on this floor.
     * This relationship is mapped as one-to-many, with the "floor" field in the Room entity serving as the reference.
     * Fetching is performed lazily, and all operations on this list cascade to the associated Room entities.
     */
    @OneToMany(mappedBy = "floor", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private List<Room> rooms;

    /**
     * Returns a string representation of the Floor object, including its id, name, theme, and associated rooms.
     *
     * @return A string representation of the Floor instance.
     */
    @Override
    public String toString() {
        return "Floor{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", theme='" + theme + '\'' +
                ", rooms=" + rooms +
                '}';
    }
}
